# Generated by Django 2.2.4 on 2020-04-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='Name',
            field=models.CharField(help_text='Enter name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='Shop_Name',
            field=models.CharField(help_text='Enter shop_name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='Status',
            field=models.CharField(help_text='Enter status', max_length=150, null=True),
        ),
    ]
